import http from './http'

export const registerUser = (payload) => http.post('/auth/register', payload)
export const sendRegisterSMSCode = (payload) => http.post('/auth/register/send-code', payload)
export const loginUser = (payload) => http.post('/auth/login', payload)
export const loginUserByPhone = (payload) => http.post('/auth/login-by-phone', payload)
export const sendLoginSMSCode = (payload) => http.post('/auth/login/send-code', payload)
export const sendPasswordResetCode = (payload) => http.post('/auth/password/send-code', payload)
export const resetPasswordByPhone = (payload) => http.post('/auth/password/reset', payload)
export const devResetPassword = (payload) => http.post('/auth/dev/reset-password', payload)
export const fetchPublicPackages = () => http.get('/packages')
export const fetchCustomerStore = (id) => http.get(`/customer/stores/${id}`)
export const fetchCustomerStoreProducts = (storeId) => http.get(`/customer/store/${storeId}/products`)
export const submitCustomerLead = (id, payload) => http.post(`/customer/stores/${id}/leads`, payload)
export const createCustomerStoreOrder = (payload) => http.post('/customer/orders', payload)
export const fetchCustomerOrder = (orderNo) => http.get(`/customer/orders/${orderNo}`)
export const retryCustomerOrderPayment = (orderNo, payload) => http.post(`/customer/orders/${orderNo}/retry`, payload)
export const fetchUserProfile = () => http.get('/user/profile')
export const sendBindEmailCode = (payload) => http.post('/user/email/send-code', payload)
export const bindUserEmail = (payload) => http.post('/user/email/bind', payload)
export const fetchUserOrders = () => http.get('/user/orders')
export const fetchUserOrderDetail = (orderNo) => http.get(`/user/orders/${orderNo}`)
export const createUserOrder = (payload) => http.post('/user/orders', payload)
export const cancelUserOrder = (orderNo) => http.post(`/user/orders/${orderNo}/cancel`)

export const merchantRegister = (payload) => http.post('/merchant/register', payload)
export const sendMerchantRegisterSMSCode = (payload) => http.post('/merchant/register/send-code', payload)
export const merchantLogin = (payload) => http.post('/merchant/login', payload)
export const fetchMerchantInfo = () => http.get('/merchant/info')
export const checkMerchantSubscription = () => http.get('/merchant/check-subscription')
export const fetchMerchantSubscription = () => http.get('/merchant/subscription')
export const createMerchantSubscriptionOrder = (payload) => http.post('/merchant/subscription/orders', payload)
export const fetchMerchantSubscriptionOrder = (orderNo) => http.get(`/merchant/subscription/orders/${orderNo}`)
export const fetchMerchantAIInsights = () => http.get('/merchant/ai/insights')
export const fetchMerchantLeads = (params) => http.get('/merchant/leads', { params })
export const fetchMerchantLeadStats = () => http.get('/merchant/leads/stats')
export const updateMerchantInfo = (payload) => http.put('/merchant/info', payload)
export const fetchMerchantPaymentConfig = () => http.get('/merchant/payment-config')
export const saveMerchantPaymentConfig = (payload) => http.put('/merchant/payment-config', payload)
export const fetchMerchantStores = (params) => http.get('/merchant/stores', { params })
export const createMerchantStore = (payload) => http.post('/merchant/stores', payload)
export const updateMerchantStore = (id, payload) => http.put(`/merchant/stores/${id}`, payload)
export const deleteMerchantStore = (id) => http.delete(`/merchant/stores/${id}`)
export const fetchMerchantStoreProducts = (storeId, params) => http.get(`/merchant/stores/${storeId}/products`, { params })
export const createMerchantStoreProduct = (payload) => http.post('/merchant/products', payload)
export const updateMerchantStoreProduct = (id, payload) => http.put(`/merchant/products/${id}`, payload)
export const deleteMerchantStoreProduct = (id) => http.delete(`/merchant/products/${id}`)
export const fetchMerchantOrders = (params) => http.get('/merchant/orders', { params })
export const fetchMerchantRefunds = () => http.get('/merchant/refunds')
export const fetchMerchantOrderDetail = (id) => http.get(`/merchant/orders/${id}`)
export const acceptMerchantOrder = (id) => http.put(`/merchant/orders/${id}/accept`)
export const completeMerchantOrder = (id) => http.put(`/merchant/orders/${id}/complete`)
export const closeMerchantOrder = (id) => http.put(`/merchant/orders/${id}/close`)
export const updateMerchantOrderNote = (id, payload) => http.put(`/merchant/orders/${id}/note`, payload)
export const refundMerchantOrder = (id, payload) => http.post(`/merchant/orders/${id}/refund`, payload)
export const fetchMerchantPromotions = (params) => http.get('/merchant/promotions', { params })
export const generateMerchantPromotionDraft = (payload = {}) => http.post('/merchant/promotions/ai-draft', payload)
export const createMerchantPromotion = (payload) => http.post('/merchant/promotions', payload)
export const updateMerchantPromotion = (id, payload) => http.put(`/merchant/promotions/${id}`, payload)
export const deleteMerchantPromotion = (id) => http.delete(`/merchant/promotions/${id}`)

export const adminLogin = (payload) => http.post('/admin/auth/login', payload)
export const fetchDashboard = (params) => http.get('/admin/dashboard', { params })
export const fetchAuditLogs = (params) => http.get('/admin/audit-logs', { params })
export const fetchMerchants = (params) => http.get('/admin/merchants', { params })
export const fetchMerchantPlans = () => http.get('/admin/merchant-plans')
export const createMerchantPlan = (payload) => http.post('/admin/merchant-plans', payload)
export const updateMerchantPlan = (id, payload) => http.put(`/admin/merchant-plans/${id}`, payload)
export const fetchMerchantDetail = (id) => http.get(`/admin/merchants/${id}`)
export const fetchAdminMerchantPaymentConfig = (id) => http.get(`/admin/merchants/${id}/payment-config`)
export const reviewAdminMerchantPaymentConfig = (id, payload) => http.put(`/admin/merchants/${id}/payment-config`, payload)
export const updateMerchantStatus = (id, payload) => http.put(`/admin/merchants/${id}/status`, payload)
export const openMerchantSubscription = (id, payload) => http.post(`/admin/merchants/${id}/subscription/open`, payload)
export const stopMerchantSubscription = (id) => http.post(`/admin/merchants/${id}/subscription/stop`)
export const fetchAdminMerchantStores = (id, params) => http.get(`/admin/merchants/${id}/stores`, { params })
export const createAdminMerchantStore = (id, payload) => http.post(`/admin/merchants/${id}/stores`, payload)
export const updateAdminMerchantStore = (id, storeId, payload) => http.put(`/admin/merchants/${id}/stores/${storeId}`, payload)
export const disableAdminMerchantStore = (id, storeId) => http.delete(`/admin/merchants/${id}/stores/${storeId}`)
export const fetchAdminMerchantLeads = (id, params) => http.get(`/admin/merchants/${id}/leads`, { params })
export const fetchAdminMerchantLeadStats = (id) => http.get(`/admin/merchants/${id}/leads/stats`)
export const updateAdminMerchantLead = (id, leadId, payload) => http.put(`/admin/merchants/${id}/leads/${leadId}`, payload)
export const fetchAdminMerchantAIInsights = (id) => http.get(`/admin/merchants/${id}/ai/insights`)
export const fetchAdminMerchantSubscriptionOrders = (id) => http.get(`/admin/merchants/${id}/subscription-orders`)
export const fetchAdminMerchantStoreOrders = (id, params) => http.get(`/admin/merchants/${id}/store-orders`, { params })
export const fetchAdminMerchantSettlementPrepare = (id) => http.get(`/admin/merchants/${id}/settlement-prepare`)
export const fetchAdminMerchantSettlements = (id) => http.get(`/admin/merchants/${id}/settlements`)
export const createAdminMerchantSettlement = (id, payload) => http.post(`/admin/merchants/${id}/settlements`, payload)
export const markAdminMerchantSettlementPaid = (id, payload) => http.put(`/admin/settlements/${id}/paid`, payload)
export const exportAdminMerchantSettlement = (id) => http.get(`/admin/settlements/${id}/export`, { responseType: 'blob' })
export const fetchCustomerProfiles = (params) => http.get('/admin/customers', { params })
export const fetchUsers = (params) => http.get('/admin/users', { params })
export const updateUserStatus = (id, payload) => http.put(`/admin/users/${id}/status`, payload)
export const updateUserPhone = (id, payload) => http.put(`/admin/users/${id}/phone`, payload)
export const manualOpenMember = (id, payload) => http.post(`/admin/users/${id}/member`, payload)
export const fetchPackages = () => http.get('/admin/packages')
export const createPackage = (payload) => http.post('/admin/packages', payload)
export const updatePackage = (id, payload) => http.put(`/admin/packages/${id}`, payload)
export const fetchOrders = () => http.get('/admin/orders')
export const fetchPayments = () => http.get('/admin/payments')
export const fetchRefunds = () => http.get('/admin/refunds')
export const refundAdminOrder = (id, payload) => http.post(`/admin/orders/${id}/refund`, payload)
export const fetchCards = () => http.get('/admin/cards')
export const batchCards = (payload) => http.post('/admin/cards/batch', payload)
export const fetchConfigs = () => http.get('/admin/configs')
export const saveConfigs = (payload) => http.post('/admin/configs', payload)
