ALTER TABLE orders
  ADD COLUMN share_code VARCHAR(40) NULL,
  ADD INDEX idx_orders_share_code (share_code);

CREATE TABLE IF NOT EXISTS referral_coupons (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  deleted_at DATETIME(3) NULL,
  merchant_id BIGINT UNSIGNED NOT NULL,
  store_id BIGINT UNSIGNED NOT NULL,
  share_campaign_id BIGINT UNSIGNED NULL,
  order_id BIGINT UNSIGNED NULL,
  coupon_no VARCHAR(60) NOT NULL,
  owner_phone VARCHAR(30) NULL,
  owner_type VARCHAR(30) NULL,
  title VARCHAR(120) NULL,
  amount BIGINT NOT NULL DEFAULT 0,
  threshold BIGINT NOT NULL DEFAULT 0,
  status VARCHAR(20) DEFAULT 'unused',
  valid_from DATETIME(3) NULL,
  valid_to DATETIME(3) NULL,
  used_at DATETIME(3) NULL,
  remark VARCHAR(255) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY idx_referral_coupons_coupon_no (coupon_no),
  KEY idx_referral_coupons_deleted_at (deleted_at),
  KEY idx_referral_coupons_merchant_id (merchant_id),
  KEY idx_referral_coupons_store_id (store_id),
  KEY idx_referral_coupons_share_campaign_id (share_campaign_id),
  KEY idx_referral_coupons_order_id (order_id),
  KEY idx_referral_coupons_owner_phone (owner_phone),
  KEY idx_referral_coupons_owner_type (owner_type),
  KEY idx_referral_coupons_status (status),
  CONSTRAINT fk_referral_coupons_merchant FOREIGN KEY (merchant_id) REFERENCES merchants(id),
  CONSTRAINT fk_referral_coupons_store FOREIGN KEY (store_id) REFERENCES stores(id),
  CONSTRAINT fk_referral_coupons_share_campaign FOREIGN KEY (share_campaign_id) REFERENCES share_campaigns(id),
  CONSTRAINT fk_referral_coupons_order FOREIGN KEY (order_id) REFERENCES orders(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
