CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  deleted_at DATETIME(3) NULL,
  actor_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  actor_type VARCHAR(30) NULL,
  actor_name VARCHAR(120) NULL,
  action VARCHAR(80) NULL,
  target_type VARCHAR(60) NULL,
  target_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  target_name VARCHAR(160) NULL,
  merchant_id BIGINT UNSIGNED NULL,
  ip VARCHAR(80) NULL,
  user_agent VARCHAR(255) NULL,
  detail JSON NULL,
  PRIMARY KEY (id),
  INDEX idx_audit_logs_deleted_at (deleted_at),
  INDEX idx_audit_logs_actor_id (actor_id),
  INDEX idx_audit_logs_actor_type (actor_type),
  INDEX idx_audit_logs_action (action),
  INDEX idx_audit_logs_target_type (target_type),
  INDEX idx_audit_logs_target_id (target_id),
  INDEX idx_audit_logs_merchant_id (merchant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
